<?php

include_once "circle.php";
class cylinder extends circle
{   public $height;
    public function __construct($name, $radius,$height)
    {
        $this->height=$height;
        parent::__construct($name, $radius);
    }
    public function calArea()
    {
        return parent::calArea()*2+parent::calPerimeter()*$this->height; // TODO: Change the autogenerated stub
    }
    public function volume(){
        return parent::calArea()*$this->height;
    }
}